import { ArrowsOutIcon, ArrowUUpLeftIcon, CircleIcon, CrosshairIcon, CursorIcon, FrameCornersIcon, ImageIcon, MonitorIcon, MouseSimpleIcon, SparkleIcon, SquaresFourIcon } from '@phosphor-icons/react';
import type { AspectRatio, EditorTab, EffectMode, MotionClip, Project, VisualSettings } from '../../shared';
import { DEFAULT_SETTINGS, FRAME_LIMITS, PRESETS } from '../../shared';
import { hasEmbeddedCursor } from '../engine';
import { formatDegrees, formatMultiplier, formatPercent, formatPixels, formatSeconds, t } from '../i18n';
import { IconButton, Segmented, Slider, Toggle } from './Controls';
import { BackgroundPicker } from './BackgroundPicker';

export interface InspectorProps {
  project: Project; tab: EditorTab; onTab: (tab: EditorTab) => void;
  onSettings: (settings: Partial<VisualSettings>) => void;
  onPreset: (preset: EffectMode) => void; selectedClip?: MotionClip;
  onClip: (id: string, patch: Partial<MotionClip>) => void;
  onDeleteClip: (id: string) => void; onTrim: (start: number, end: number) => void;
}
const TAB_ICONS = { motion: SparkleIcon, cursor: CursorIcon, background: ImageIcon, canvas: FrameCornersIcon };
const PRESET_ICONS = { focus: CrosshairIcon, cinematic: SquaresFourIcon, orbit: ArrowsOutIcon, overview: MonitorIcon };
const PRESET_HINTS = { focus: 'focusHint', cinematic: 'cinematicHint', orbit: 'orbitHint', overview: 'overviewHint' } as const;
const TABS: EditorTab[] = ['motion', 'cursor', 'background', 'canvas'];

export function Inspector({ project, tab, onTab, onSettings, onPreset, selectedClip, onClip, onDeleteClip, onTrim }: InspectorProps) {
  const s = project.settings; const copy = t.editor; const embeddedCursor = hasEmbeddedCursor(project);
  return <aside className="inspector"><div className="inspector-tabs" role="tablist">{TABS.map((item) => { const Glyph = TAB_ICONS[item]; return <button role="tab" type="button" aria-selected={tab === item} key={item} className={tab === item ? 'selected' : ''} onClick={() => onTab(item)}><Glyph size={19} /><span>{copy[item]}</span></button>; })}</div><div className="inspector-scroll" key={tab}>
    <div className="inspector-heading"><h2>{copy[`${tab}Title`]}</h2><p>{copy[`${tab}Hint`]}</p></div>
    {tab === 'motion' && <><div className="control-section"><div className="section-caption">{copy.presets}<IconButton icon={ArrowUUpLeftIcon} label={copy.reset} onClick={() => onSettings({ ...DEFAULT_SETTINGS, background: s.background, aspect: s.aspect })} size={15} /></div><div className="preset-grid">{(Object.keys(PRESETS) as EffectMode[]).map((preset) => { const Glyph = PRESET_ICONS[preset]; return <button className={`preset ${s.mode === preset ? 'selected' : ''}`} key={preset} onClick={() => onPreset(preset)} type="button" title={copy[PRESET_HINTS[preset]]}><span className={`preset-art ${preset}`}><span className="mini-screen" /><Glyph className="preset-glyph" size={20} /></span><span>{copy[preset]}</span>{s.mode === preset && <span className="selection-dot" />}</button>; })}</div></div><div className="control-section"><Toggle label={copy.autoZoom} checked={s.autoZoom} onChange={(autoZoom) => onSettings({ autoZoom })} /><Toggle label={copy.followCursor} checked={s.followCursor} onChange={(followCursor) => onSettings({ followCursor })} /><div className="slider-stack"><Slider label={copy.zoomAmount} value={s.zoom} min={1} max={3} step={0.05} display={formatMultiplier(s.zoom)} onChange={(zoom) => onSettings({ zoom })} /><Slider label={copy.tiltAmount} value={s.tilt} min={0} max={30} display={formatDegrees(s.tilt)} onChange={(tilt) => onSettings({ tilt })} /><Slider label={copy.easing} value={s.easing} min={0.2} max={1.5} step={0.1} display={formatSeconds(s.easing)} onChange={(easing) => onSettings({ easing })} /></div></div></>}
    {tab === 'cursor' && <>{!embeddedCursor && <div className="control-section"><p className="section-caption">{copy.cursorStyle}</p><Segmented label={copy.cursorStyle} value={s.cursor} onChange={(cursor) => onSettings({ cursor })} options={[{ value: 'arrow', label: copy.arrow, icon: CursorIcon }, { value: 'dot', label: copy.dot, icon: CircleIcon }, { value: 'none', label: copy.none }]} /><div className="slider-stack"><Slider label={copy.cursorSize} value={s.cursorSize} min={14} max={56} display={formatPixels(s.cursorSize)} onChange={(cursorSize) => onSettings({ cursorSize })} /></div></div>}<div className="control-section"><Toggle label={copy.clickEffect} checked={s.clickEffect} onChange={(clickEffect) => onSettings({ clickEffect })} /><Toggle label={copy.spotlight} checked={s.spotlight} onChange={(spotlight) => onSettings({ spotlight })} /></div><div className="inspector-note"><MouseSimpleIcon size={18} /><p>{embeddedCursor ? t.recording.nativeCursorNote : project.sourceType === 'demo' ? copy.demoHint : t.recording.separateCursorNote}</p></div></>}
    {tab === 'background' && <><BackgroundPicker settings={s} onSettings={onSettings} /><div className="control-section slider-stack"><Slider label={copy.padding} value={s.padding} min={0} max={22} display={formatPercent(s.padding)} onChange={(padding) => onSettings({ padding })} /><Slider label={copy.radius} value={s.radius} min={0} max={50} display={formatPixels(s.radius)} onChange={(radius) => onSettings({ radius })} /><Slider label={t.frame.edgeGlass} value={s.edgeGlass ?? DEFAULT_SETTINGS.edgeGlass ?? 0} min={0} max={FRAME_LIMITS.edgeGlass} display={formatPercent(s.edgeGlass ?? DEFAULT_SETTINGS.edgeGlass ?? 0)} onChange={(edgeGlass) => onSettings({ edgeGlass })} /><p className="field-hint">{t.frame.edgeGlassHint}</p><Slider label={copy.shadow} value={s.shadow} min={0} max={100} display={formatPercent(s.shadow)} onChange={(shadow) => onSettings({ shadow })} /></div></>}
    {tab === 'canvas' && <><div className="control-section"><p className="section-caption">{copy.aspectRatio}</p><div className="aspect-grid">{(['16:9', '9:16', '1:1', '4:3'] as AspectRatio[]).map((aspect, index) => <button type="button" key={aspect} className={`aspect-option ${s.aspect === aspect ? 'selected' : ''}`} onClick={() => onSettings({ aspect })}><span className={`aspect-symbol aspect-${index}`} /><strong>{aspect}</strong><small>{[copy.landscape, copy.portrait, copy.square, copy.classic][index]}</small></button>)}</div></div><div className="control-section"><p className="section-caption">{copy.trim}</p><div className="number-pair"><label>{copy.trimStart}<input type="number" min={0} max={project.trimEnd - 0.2} step={0.1} value={Number(project.trimStart.toFixed(1))} onChange={(event) => onTrim(Math.max(0, Math.min(Number(event.currentTarget.value), project.trimEnd - 0.2)), project.trimEnd)} /></label><label>{copy.trimEnd}<input type="number" min={project.trimStart + 0.2} max={project.duration} step={0.1} value={Number(project.trimEnd.toFixed(1))} onChange={(event) => onTrim(project.trimStart, Math.min(project.duration, Math.max(Number(event.currentTarget.value), project.trimStart + 0.2)))} /></label></div><p className="field-hint">{copy.trimHint}</p></div></>}
    {tab === 'motion' && selectedClip && <div className="control-section shot-inspector"><p className="section-caption">{copy.shotSettings}<span className="small-tag">{selectedClip.manual ? copy.manualShot : copy.automaticShot}</span></p><Toggle label={copy.enabled} checked={selectedClip.enabled} onChange={(enabled) => onClip(selectedClip.id, { enabled })} /><div className="number-pair"><label>{copy.shotStart}<input type="number" min={0} max={selectedClip.end - 0.2} step={0.1} value={Number(selectedClip.start.toFixed(1))} onChange={(event) => onClip(selectedClip.id, { start: Math.max(0, Math.min(Number(event.currentTarget.value), selectedClip.end - 0.2)) })} /></label><label>{copy.shotEnd}<input type="number" min={selectedClip.start + 0.2} max={project.duration} step={0.1} value={Number(selectedClip.end.toFixed(1))} onChange={(event) => onClip(selectedClip.id, { end: Math.min(project.duration, Math.max(Number(event.currentTarget.value), selectedClip.start + 0.2)) })} /></label></div><Slider label={copy.zoomAmount} value={selectedClip.zoom} min={1} max={3} step={0.05} display={formatMultiplier(selectedClip.zoom)} onChange={(zoom) => onClip(selectedClip.id, { zoom })} /><label className="select-control">{copy.shotMode}<select value={selectedClip.mode} onChange={(event) => onClip(selectedClip.id, { mode: event.currentTarget.value as EffectMode })}>{(Object.keys(PRESETS) as EffectMode[]).map((preset) => <option key={preset} value={preset}>{copy[preset]}</option>)}</select></label><button type="button" className="text-button danger" onClick={() => onDeleteClip(selectedClip.id)}>{copy.deleteShot}</button></div>}
  </div><div className="inspector-footer"><span className="status-dot" />{copy.localOnly}</div></aside>;
}
